# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    name: Tags
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template
    required: true

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true
    required: false

categories:
    name: Catégories
    slug: categories
    singular_name: Catégorie
    singular_slug: categorie
    behaves_like: catégories
    multiple: true
    options: [ technologie, business, hébergement, e-commerce, web-design, infos ]
    required: true
    listing_template: category.twig
    listing_records: 4
